In [1]:
# import pandas
import pandas as pd

In [2]:
# Import the excel data from Brightspace
df= pd.read_excel(r"C:\Users\Legion 5\Downloads\sales (1).xlsx")
df

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,Unnamed: 8,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,NaN,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,NaN,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...
30608,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...
30610,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...

In [3]:
# Deleting columns that we don't use
df = df.drop(columns=['year', 'release_date', 'title', 'international_box_office', 
                    'domestic_box_office', 'Unnamed: 8', 'theatre_count', 'avg run per theatre', 'keywords', 'creative_type' ])

In [4]:
# split the url and change de data type
movie_name= df.url.str.split('/', expand=True)
movie_name

,0,1,2,3,4
0,https:,,www.the-numbers.com,movie,Bakha-Satang-(S-Korea)
1,https:,,www.the-numbers.com,movie,Antitrust
2,https:,,www.the-numbers.com,movie,Santitos
3,https:,,www.the-numbers.com,movie,Frank-McKlusky-C-I
4,https:,,www.the-numbers.com,movie,Walk-to-Remember-A
...,...,...,...,...,...
30607,https:,,www.the-numbers.com,movie,Jokbeoldu-sinmun-iyagi-(2020-South-Korea)
30608,https:,,www.the-numbers.com,movie,My-Salinger-Year-(Canada)
30609,https:,,www.the-numbers.com,movie,Escort-Vehicle-36-(2020-China)
30610,https:,,www.the-numbers.com,movie,Dry-The-(Australia)
30611,https:,,www.the-numbers.com,movie,Posledniy-bogatyr-Koren-Zla-(2021-Russia)

In [5]:
#Add the names of the movie to the file with the name "title"
df["title"] = movie_name[:][4]
df

,genre,worldwide_box_office,production_budget,opening_weekend,runtime,url,title
0,Drama,76576.0,NaN,NaN,129.0,https://www.the-numbers.com/movie/Bakha-Satang...,Bakha-Satang-(S-Korea)
1,Thriller/Suspense,17865209.0,30000000.0,5486209.0,NaN,https://www.the-numbers.com/movie/Antitrust,Antitrust
2,NaN,NaN,NaN,NaN,105.0,https://www.the-numbers.com/movie/Santitos,Santitos
3,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,Frank-McKlusky-C-I
4,Drama,46060861.0,11000000.0,12177488.0,NaN,https://www.the-numbers.com/movie/Walk-to-Reme...,Walk-to-Remember-A
...,...,...,...,...,...,...,...
30607,Documentary,12356.0,NaN,NaN,168.0,https://www.the-numbers.com/movie/Jokbeoldu-si...,Jokbeoldu-sinmun-iyagi-(2020-South-Korea)
30608,Drama,968849.0,NaN,28851.0,101.0,https://www.the-numbers.com/movie/My-Salinger-...,My-Salinger-Year-(Canada)
30609,Action,240000.0,NaN,NaN,85.0,https://www.the-numbers.com/movie/Escort-Vehic...,Escort-Vehicle-36-(2020-China)
30610,Thriller/Suspense,17351923.0,NaN,119364.0,118.0,https://www.the-numbers.com/movie/Dry-The-(Aus...,Dry-The-(Australia)
30611,Adventure,33396899.0,NaN,NaN,NaN,https://www.the-numbers.com/movie/Posledniy-bo...,Posledniy-bogatyr-Koren-Zla-(2021-Russia)

In [6]:
# Make url the first column 
first_column = df.pop('url')
df.insert(0, 'url', first_column)

In [7]:
# Removing the NaN and change it to 0.0
df= df.fillna(0)
df

,url,genre,worldwide_box_office,production_budget,opening_weekend,runtime,title
0,https://www.the-numbers.com/movie/Bakha-Satang...,Drama,76576.0,0.0,0.0,129.0,Bakha-Satang-(S-Korea)
1,https://www.the-numbers.com/movie/Antitrust,Thriller/Suspense,17865209.0,30000000.0,5486209.0,0.0,Antitrust
2,https://www.the-numbers.com/movie/Santitos,0,0.0,0.0,0.0,105.0,Santitos
3,https://www.the-numbers.com/movie/Frank-McKlus...,0,0.0,0.0,0.0,0.0,Frank-McKlusky-C-I
4,https://www.the-numbers.com/movie/Walk-to-Reme...,Drama,46060861.0,11000000.0,12177488.0,0.0,Walk-to-Remember-A
...,...,...,...,...,...,...,...
30607,https://www.the-numbers.com/movie/Jokbeoldu-si...,Documentary,12356.0,0.0,0.0,168.0,Jokbeoldu-sinmun-iyagi-(2020-South-Korea)
30608,https://www.the-numbers.com/movie/My-Salinger-...,Drama,968849.0,0.0,28851.0,101.0,My-Salinger-Year-(Canada)
30609,https://www.the-numbers.com/movie/Escort-Vehic...,Action,240000.0,0.0,0.0,85.0,Escort-Vehicle-36-(2020-China)
30610,https://www.the-numbers.com/movie/Dry-The-(Aus...,Thriller/Suspense,17351923.0,0.0,119364.0,118.0,Dry-The-(Australia)
30611,https://www.the-numbers.com/movie/Posledniy-bo...,Adventure,33396899.0,0.0,0.0,0.0,Posledniy-bogatyr-Koren-Zla-(2021-Russia)

In [35]:
# Export to CSV file
df.to_csv('', index=False)